spring.application.name=kriba
server.port=8080

spring.datasource.url=jdbc:mysql://193.70.44.51:3306/Kriba
spring.datasource.username=Kriba
spring.datasource.password=Kriba

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cache.type=redis
spring.data.redis.host=193.70.44.51
spring.data.redis.port=6379
spring.data.redis.password=Kriba

apiKey=89b05e429e84d72660d701fd6af51123
apiKeySummarize=AIzaSyDxCFXAPvPxpTAzknO17_pUCurfjd8OO9U
geminiModel=gemini-3.1-flash-lite