spring.application.name=kriba
server.port=8080
server.address=0.0.0.0

app.base-url=https://kriba-d08ba5-193-70-44-51.sslip.io
frontend.base-url=https://kriba-b33e18-193-70-44-51.sslip.io

spring.datasource.url=jdbc:mysql://193.70.44.51:3306/Kriba
spring.datasource.username=Kriba
spring.datasource.password=Kriba

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cache.type=redis
spring.data.redis.host=193.70.44.51
spring.data.redis.port=6379
spring.data.redis.password=Kriba

apiKey=85c17d7ad5e92326258c01df91c5daca
apiKeySummarize=AIzaSyAI0LvDRCPsgCRt3AlYrWn_RHsnR1G5BmI
geminiModel=gemini-3.1-flash-lite

resilience4j.circuitbreaker.instances.gnewsApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.gnewsApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.gnewsApi.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.gnewsApi.permitted-number-of-calls-in-half-open-state=3

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000